version: '2'

services:
  db:
      image: postgres
  web:
      build: ./web-app
      user: nobody
      command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
      volumes:
        - ./web-app:/code
      expose:
        - "8000"
      depends_on:
        - db
  nginx:
     image: nginx:latest
     ports:
       - "8000:8000"
     volumes:
       - ./nginx/config:/etc/nginx/conf.d
     depends_on:
       - web