# Generated by Django 2.1.5 on 2019-01-30 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190129_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['time'], 'permissions': (('confirm_order', 'Can change order status'), ('change_order_info', 'Can change order information'), ('create_order', 'Can create'))},
        ),
    ]
