# Generated by Django 2.1.5 on 2019-01-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190130_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ManyToManyField(null=True, related_name='owner_order', to='home.Owner'),
        ),
    ]
