# Generated by Django 2.1.5 on 2019-01-30 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190130_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(default=233334, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='home.Driver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ManyToManyField(related_name='order', to='home.Owner'),
        ),
    ]
