# Generated by Django 2.1.5 on 2019-01-30 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190130_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Driver'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='order',
            field=models.ManyToManyField(null=True, to='home.Order'),
        ),
    ]
