# Generated by Django 2.1.5 on 2019-01-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190130_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='order',
            field=models.ManyToManyField(to='home.Order'),
        ),
    ]
