# Generated by Django 2.1.5 on 2019-01-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190130_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='departure',
            field=models.CharField(default=463, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(default=2, max_length=16),
            preserve_default=False,
        ),
    ]
