# Generated by Django 2.1.5 on 2019-01-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190130_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['datetime'], 'permissions': (('confirm_order', 'Can change order status'), ('change_order_info', 'Can change order information'), ('create_order', 'Can create'))},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='time',
            new_name='datetime',
        ),
    ]
