# Generated by Django 2.1.5 on 2019-01-30 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190130_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='departure',
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Driver'),
        ),
    ]
