# Generated by Django 2.1.5 on 2019-01-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190130_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='departure',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
    ]
