# Generated by Django 2.1.5 on 2019-01-31 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_order_departure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['aptime'], 'permissions': (('confirm_order', 'Can change order status'), ('change_order_info', 'Can change order information'), ('create_order', 'Can create'))},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='datetime',
            new_name='aptime',
        ),
    ]
