# Generated by Django 2.1.5 on 2019-02-03 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190131_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='passenger',
        ),
    ]
