# Generated by Django 2.1.5 on 2019-02-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_order_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='passenger',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
    ]
