# Generated by Django 2.1.5 on 2019-02-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_driver_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='departure',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
