# Generated by Django 2.1.5 on 2019-02-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20190205_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='departure',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.CharField(default=67, max_length=200),
            preserve_default=False,
        ),
    ]
