# Generated by Django 2.1.5 on 2019-02-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20190205_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Request'), ('s', 'Shared'), ('c', 'Confirmed'), ('f', 'Finished')], default='r', help_text='order', max_length=1),
        ),
    ]
